# Generated by Django 3.1 on 2020-08-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookquery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookquery',
            name='any_field',
            field=models.CharField(default='', max_length=1000, verbose_name='Wildcard search'),
            preserve_default=False,
        ),
    ]
