# Generated by Django 3.1 on 2020-08-31 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookquery', '0003_auto_20200831_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookquery',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bookquery',
            name='title',
        ),
    ]
